
module.exports = {
  aliens: require('./aliens'),
  amphibians: require('./amphibians'),
  bats: require('./bats'),
  bears: require('./bears'),
  birds: require('./birds'),
  birdOfPreys: require('./bird_of_preys'),
  cats: require('./cats'),
  cows: require('./cows'),
  crabs: require('./crabs'),
  deers: require('./deers'),
  dogs: require('./dogs'),
  elephants: require('./elephants'),
  fishs: require('./fishs'),
  horses: require('./horses'),
  insects: require('./insects'),
  lions: require('./lions'),
  marineMammals: require('./marine_mammals'),
  monkeys: require('./monkeys'),
  mouses: require('./mouses'),
  owls: require('./owls'),
  parrots: require('./parrots'),
  pigs: require('./pigs'),
  rabbits: require('./rabbits'),
  reptiles: require('./reptiles'),
  rodents: require('./rodents'),
  sheeps: require('./sheeps'),
  turtles: require('./turtles'),
  wolfs: require('./wolfs')
}
